### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by SGXiaoLin** [DevYao/JSONConverter#12]
在iOS-oc使用时，如果数据源有空list的情况下，例： 
"expand" : {

          },

这样的，会直接崩溃，查看代码这边简单修改为

mutating func removeLastChar() {
        if !self.isEmpty {
            let range = self.index(endIndex, offsetBy: -1)..<self.endIndex
            self.removeSubrange(range)
        }
    }
增加了一个字符串为空的判断。

**Comment by vvkeep** [comment]
欢迎提交pr哦
