### ISSUE TITLE
参数设置怎么像1.2那样放到下面？

### ISSUE THREAD

**Issue by IvanYue** [DevYao/JSONConverter#15]

**Comment by DevYao** [comment]
e ... 新的版本就是新建个Controller 设置了，后面会新增很多设置项，主页面下面放不下，你是觉得这样的设计不友好吗

**Comment by vvkeep** [comment]
e ... 新的版本就是新建个Controller 设置了，后面会新增很多设置项，考虑把主页面下面放不下，你是觉得这样的设计不友好吗

如果你不喜欢新版本的设计，可以下载1.2-release 的代码，把检查版本的代码注释掉，重新编译一个包使用
