### ISSUE TITLE
代码高亮

### ISSUE THREAD

**Issue by L1cardo** [DevYao/JSONConverter#17]
我看到代码高亮部分你是自定义的关键字、颜色等
可以考虑[Highlightr](https://github.com/raspu/Highlightr)这个库进行代码高亮

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by vvkeep** [comment]
在做富文本的功能时，确实有尝试使用过这个库，尝试了一些主题和语言，始终不能找到满意的配色方案（可能是我对这个库不够了解），最终还是决定使用目前的方式来实现，但还是感谢你的建议，如果你对这个项目感兴趣，欢迎和我一起维护它

**Comment by L1cardo** [comment]
> 在做富文本的功能时，确实有尝试使用过这个库，尝试了一些主题和语言，始终不能找到满意的配色方案（可能是我对这个库不够了解），最终还是决定使用目前的方式来实现，但还是感谢你的建议，如果你对这个项目感兴趣，欢迎和我一起维护它

那就麻烦你把swift的代码高亮做的尽可能和xcode一样，其他语言无所谓😂
一些小pr我能提的也会帮忙的

**Comment by vvkeep** [comment]
最终决定还是使用 Highlightr😝
