### ISSUE TITLE
内容有表情会异常卡死

### ISSUE THREAD

**Issue by KenmuHuang** [DevYao/JSONConverter#18]
比如：
{
     "id": "1005033383",
    "nickname": "编码器🤢",
    "is_teacher": 0
}

异常定位：
class JSONHightTextStorage: NSTextStorage {
    
    var _string = NSMutableAttributedString()
        
    override var string: String {
        return _string.string
    }
    
    override func attributes(at location: Int, effectiveRange range: NSRangePointer?) -> [NSAttributedString.Key : Any] {
        return _string .attributes(at: location, effectiveRange: range) // 这里报错
    }
![截屏2020-09-15 18 07 25](https://user-images.githubusercontent.com/11454770/93197939-e2216200-f77e-11ea-833f-c89688b6b7d8.png)

**Comment by vvkeep** [comment]
多谢你的反馈，已经修复这个问题
