### ISSUE TITLE
安装完后无法打开，图标换换吧

### ISSUE THREAD

**Issue by RQ0588** [DevYao/JSONConverter#22]
OS 10.15.6 
========================================================
System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1
========================================================
终端命令使用了
简介中没有那个警告覆盖选项
下载代码运行可以的

**Comment by vvkeep** [comment]
下载代码编译，把编译的app 拖至application中，使用吧

图标有什么问题，还是我新弄的图标😢

**Comment by RQ0588** [comment]
> 下载代码编译，把编译的app 拖至application中，使用吧
> 
> 图标有什么问题，还是我新弄的图标😢

白色底，不带一丝丝圆角，看着太生硬了
![image](https://user-images.githubusercontent.com/20916477/97521574-d01b1c00-19d8-11eb-910c-476b6ec5a594.png)

**Comment by vvkeep** [comment]
好的 改一下

**Comment by stack-info** [comment]
我Fork了一个版本，图标做了圆角处理，作者可以看看，或者有需要的可以Clone我这个版本自己编译，分支在2.x
https://github.com/code-src/JSONConverter

**Comment by vvkeep** [comment]
感谢，已经合并了
