### ISSUE TITLE
老哥，是否有计划支持Flutter2.x 的空安全。

### ISSUE THREAD

**Issue by IvanYue** [DevYao/JSONConverter#26]
老哥，是否有计划支持Flutter2.x 的 Null-safety。

**Comment by vvkeep** [comment]
要等一段时间，最近没空哎😔

**Comment by vvkeep** [comment]
master 分支 尝试支持Flutter2.x 的 Null-safety，但因为没有在实际项目中使用，并不清楚目前的实现，在flutter2.x中生成的模型是否实用，还望尝试使用后告知一下 
另外有个问题，我看了开源的一些工程实现，发现有的工程 模型是 继承了 Object, 有的模型并没有继承 Object，不知Flutter 模型的主流方案是如何？
