### ISSUE TITLE
OC支持YYModel吗？

### ISSUE THREAD

**Issue by RondaHo** [DevYao/JSONConverter#34]
如题

**Comment by songxing10000** [comment]
最近也有类似的需求，经常要设置数组里装的是啥类型的元素，当时流行的是MJ和YY，如果能对这个数组里申明元素类型的方法，自动填充就好了

**Comment by vvkeep** [comment]
收到 收到，将在下个版本实现

**Comment by uxiume** [comment]
@vvkeep 我记得之前的版本支持OC的解析啊，怎么现在没了，而且今天安装了之后显示     应用程序“JSONConverter.app”无法打开。
<img width="260" alt="image" src="https://user-images.githubusercontent.com/38536031/168015843-57029999-33dd-413d-bac3-c3ab87b089c2.png">

**Comment by uxiume** [comment]
@vvkeep 
<img width="536" alt="image" src="https://user-images.githubusercontent.com/38536031/168066039-87ca06e0-d50d-4f0f-bb8a-1126044d7631.png">
这个 OC 解析的字符串错了，是 @"xxx" ，不是 "@xxx"

**Comment by uxiume** [comment]
@vvkeep ☺️

**Comment by vvkeep** [comment]
奥奥收到😂

**Comment by uxiume** [comment]
@vvkeep 我来给你点个赞👍👍👍 更新的真快

**Comment by vvkeep** [comment]
哈哈 请尝试 [2.1.0](https://github.com/vvkeep/JSONConverter/releases/tag/2.1.0)
