### ISSUE TITLE
v2.0.10 版本 dmg 文件，在 Inter CPU 的 Mac 上无法安装

### ISSUE THREAD

**Issue by LoadingMx** [DevYao/JSONConverter#35]

**Comment by songxing10000** [comment]
same
![image](https://user-images.githubusercontent.com/10040131/167981651-2c2ee00d-3658-4d86-8373-4cf49cd3d77a.png)

**Comment by songxing10000** [comment]
追加一些，细节
1、如果没有数组属性，需不需要生成这个空方法
![image](https://user-images.githubusercontent.com/10040131/167987276-2eb37c7d-31aa-4b9d-933c-340157c0bc6e.png)

**Comment by songxing10000** [comment]
2.对于自定义key的确是个问题。有的人可能总喜欢对id这个属性进行重新定义key，其实不重新定义也不会报错。如果对于一个从来不重定义key的人来说，这些自动生成的方法每次他会手动删除。而对于喜欢重定义key的人来说，他可能也只会重定义两三个key而已，如果属性过多如下图，那么他也会去手动删除这些多于keyvaalue。这是两种场景各自的问题
![image](https://user-images.githubusercontent.com/10040131/167987356-a782c6ab-ccff-481d-848f-5c6c84d022e8.png)

**Comment by vvkeep** [comment]
@songxing10000 
1. 没有数组属性将不生成`modelContainerPropertyGenericClass` 方法
2. 在设置面板增加了属性名映射的开关，可灵活选择是否生成key映射方法

**Comment by songxing10000** [comment]
nice我试试

**Comment by vvkeep** [comment]
请尝试 [2.1.0](https://github.com/vvkeep/JSONConverter/releases/tag/2.1.0)
