### ISSUE TITLE
RootClass 的名字在主界面进行配置

### ISSUE THREAD

**Issue by L1cardo** [DevYao/JSONConverter#37]
希望可以在这里进行配置，这样在创建多个model时会比较方便，而不需要每次都去点一下齿轮
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/33802186/174464705-383b41a9-d733-42fc-acb2-7f0cd484c390.png">

**Comment by vvkeep** [comment]
2.1.1 已经完成
