### ISSUE TITLE
如何打赏？

### ISSUE THREAD

**Issue by League2EB** [DevYao/JSONConverter#6]
这工具省下我许多时间，我来自台湾
非常乐意赞助您持续维护！

**Comment by vvkeep** [comment]
哈哈哈 ，我更新下这个应用的打赏功能。。

**Comment by vvkeep** [comment]
最近的提交已经修复了打赏功能，近期将添加版本更新提醒和新增flutter的Josn转换

**Comment by League2EB** [comment]
我今天早上發了打賞過去，不曉得您有沒有收到
如果可以想跟您交個朋友交流交流
這是我的微信:League2EB
期待您的回覆
