### ISSUE TITLE
转换出现崩溃

### ISSUE THREAD

**Issue by quentin996007** [DevYao/JSONConverter#7]
转换的 JSON 值如下：
{
  "message" : {
    "navigateLastPage" : 1,
    "isLastPage" : true,
    "pageSize" : 20,
    "lastPage" : 1,
    "navigatepageNums" : [
      1
    ],
    "navigateFirstPage" : 1,
    "navigatePages" : 8,
    "nextPage" : 0,
    "size" : 2,
    "pageNum" : 1,
    "list" : [
      {
        "status" : null,
        "pullUrl" : "111111",
        "groupMasterId" : "",
        "updateTime" : null,
        "totalPoint" : null,
        "createTime" : null,
        "virtualMemberCount" : null,
        "id" : 1,
        "name" : "",
        "pushUrl" : "111111",
        "appId" : "",
        "virtualPoint" : null,
        "totalTime" : null,
        "type" : "",
        "memberCount" : null,
        "sortPercent" : null,
        "sort" : null
      },
      {
        "status" : null,
        "pullUrl" : "111111",
        "groupMasterId" : "",
        "updateTime" : null,
        "totalPoint" : null,
        "createTime" : null,
        "virtualMemberCount" : null,
        "id" : 2,
        "name" : "",
        "pushUrl" : "111111",
        "appId" : "",
        "virtualPoint" : null,
        "totalTime" : null,
        "type" : "",
        "memberCount" : null,
        "sortPercent" : null,
        "sort" : null
      }
    ],
    "firstPage" : 1,
    "pages" : 1,
    "startRow" : 1,
    "hasPreviousPage" : false,
    "endRow" : 2,
    "prePage" : 0,
    "isFirstPage" : true,
    "total" : 2,
    "hasNextPage" : false
  },
  "status" : "100000"
}

**Comment by quentin996007** [comment]
问题暂时修正，我将这里的代码修改如下，完成转换。
![image](https://user-images.githubusercontent.com/7803520/61681348-c3bd0380-ad3f-11e9-8e9f-34a9bef939ae.png)

**Comment by vvkeep** [comment]
多谢了，已经解决在V1.2.2-release
