### ISSUE TITLE
最新版本闪退

### ISSUE THREAD

**Issue by League2EB** [DevYao/JSONConverter#8]
首先很遗憾没有收到您加入微信好友的邀请，日前我已经打赏了
还是希望可以跟您交流交流，有些代码的部份想跟您聊聊
我的微信：League2EB
我的QQ：3410925895
******************
系统：macOS Mojave
版本：10.14.6Beta版 (18G29g)
状况：若把整份程式码打包下来使用自己的证书签署，不会闪退
但若是使用您的Release版本直接拖曳到应用程式内，打开应用会直接闪退

**Comment by iosyaowei** [comment]
🙏，最近比较忙，没注意看，这就加了

**Comment by lfcleo** [comment]
@League2EB +1，

**Comment by League2EB** [comment]
> @League2EB +1，

@LeoDicaprio 闪退原因为签名问题，近期会将JSONConverter上架到商店去
请耐心等候，也谢谢您支持作者。

**Comment by vvkeep** [comment]
更换了打包方式，可以先试一下新版本，会不会有问题
